@HOST = http://localhost:3000


GET {{HOST}}/api/games


###
POST {{HOST}}/api/games
Content-Type: application/json

[
 {
    "name": "Mario Kart World",
    "slug": "mario-kart-world",
    "uuid": "b1c2d3e4-f5g6-h789-i012-3456789abcdef",
    "price": {
      "digital": 69.99,
      "physical": 79.99
    },
    "overview": {
      "headline": "Race around the globe in the most exciting Mario Kart adventure yet!",
      "body": "Compete in global racing events, unlock new tracks, and use wild new power-ups to leave your opponents in the dust!"
    },
    "description": "Mario Kart World brings the iconic kart-racing action to new heights! Travel across different countries and cities, each with their own unique challenges, environments, and local characters. New power-ups, like the **Turbo Glider** and **Magnet Ball**, spice up the classic gameplay.\n\nFor the first time, race through real-world locations such as Paris, Tokyo, and New York City, each featuring dynamic environments with hazards and shortcuts to master.\n\nTake on local or online multiplayer races, or challenge yourself in time trials to beat your personal best. Mario and friends are back with new moves, better kart customization, and more ways to play!\n\nUse Mario Kart Pass to unlock extra tracks, characters, and karts. Customize your ride with new parts and exclusive skins.\n\nWhether you’re a seasoned racer or a newcomer to the series, Mario Kart World offers thrills for all players!",
    "tags": ["Recent Release", "Multiplayer", "Racing"],
    "thumbnail": {
      "mobile": "/images/mario-kart-world/mario-kart-world-thumbnail-mobile.png",
      "tablet": "/images/mario-kart-world/mario-kart-world-thumbnail-tablet.png",
      "desktop": "/images/mario-kart-world/mario-kart-world-thumbnail-desktop.png"
    },
    "images": [
      {
        "mobile": "/images/mario-kart-world/mario-kart-world-hero-mobile.png",
        "tablet": "/images/mario-kart-world/mario-kart-world-hero-tablet.png",
        "desktop": "/images/mario-kart-world/mario-kart-world-hero-desktop.png",
        "youtubeUrl": "https://www.youtube.com/watch?v=abcde12345"
      },
      {
        "mobile": "/images/mario-kart-world/mario-kart-world-race-mobile.png",
        "tablet": "/images/mario-kart-world/mario-kart-world-race-tablet.png",
        "desktop": "/images/mario-kart-world/mario-kart-world-race-desktop.png"
      },
      {
        "mobile": "/images/mario-kart-world/mario-kart-world-power-ups-mobile.png",
        "tablet": "/images/mario-kart-world/mario-kart-world-power-ups-tablet.png",
        "desktop": "/images/mario-kart-world/mario-kart-world-power-ups-desktop.png"
      },
      {
        "mobile": "/images/mario-kart-world/mario-kart-world-multiplayer-mobile.png",
        "tablet": "/images/mario-kart-world/mario-kart-world-multiplayer-tablet.png",
        "desktop": "/images/mario-kart-world/mario-kart-world-multiplayer-desktop.png"
      },
      {
        "mobile": "/images/mario-kart-world/mario-kart-world-features-mobile.png",
        "tablet": "/images/mario-kart-world/mario-kart-world-features-tablet.png",
        "desktop": "/images/mario-kart-world/mario-kart-world-features-desktop.png"
      }
    ],
    "fileSize": 6.5,
    "playModes": ["TV mode", "Tabletop mode", "Handheld mode", "Online Multiplayer", "Local Multiplayer"],
    "numOfPlayer": ["1-4 players local", "1-8 players online"],
    "system": ["Switch 2"],
    "publisher": "Nintendo",
    "languages": [
      "English",
      "French",
      "German",
      "Spanish",
      "Italian",
      "Japanese"
    ],
    "franchise": "Mario",
    "ageRating": "PEGI 3",
    "genres": ["Racing", "Action"],
    "releaseDate": "June 5, 2025",
    "preOrderAvailable": false,
    "isOnSale": false,
    "nintendoPoints": 100
]

###
GET {{HOST}}/api/games/48961602-5d47-43df-97a2-ee5fc1f692e8


### Filtros combinados
POST {{HOST}}/api/games/filters
Content-Type: application/json

{
  "minPrice": 60,
  "system": [],
  "genres": [ "Adventure" ]
}

#######
USERS REQUESTS
##########


POST {{HOST}}/api/user/register
Content-Type: application/json

{
"name":"Sabrina Taraschi", 
"nickname": "sabriTest",
"email": "sabrinatesting@gmail.com", 
"password": "123456",
"region": "Europe",
"birthday": "September 25, 1996",
"profilePicture": {
    "img": "/images/profile/pikmin.svg",
    "backgroundColor": "#F3D50F"
  }
}

###
POST {{HOST}}/api/user/login
Content-Type: application/json

{
"email": "sabrinatesting@gmail.com", 
"password": "123456"
}

###
POST {{HOST}}/api/user/favorites/add
Content-Type: application/json

{
"gameId": "6878d711c8d9e0e965cac910"
}